In [2]:
import argparse
import logging
import sys
import os
import random
import json
from pathlib import Path
import numpy as np

import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader, TensorDataset
from torch.utils.data.dataset import random_split

from shrp.datasets.dataset_tokens import DatasetTokens
from shrp.git_re_basin.git_re_basin import (
    resnet18_permutation_spec,
    zoo_cnn_large_permutation_spec,
    zoo_cnn_permutation_spec)

ROOT = Path("")

ValueError: source code string cannot contain null bytes

In [2]:
zoo_path = Path("/ds2/model_zoos/zoos_v2/MNIST/tune_zoo_mnist_uniform/")

result_key_list = ["test_acc", "training_iteration"]
config_key_list = []
property_keys = {
    "result_keys": result_key_list,
    "config_keys": config_key_list
}
tokensize=0
permutation_spec = zoo_cnn_permutation_spec()

In [3]:
for rdx in [zoo_path.absolute()]:
    a = [f for f in rdx.iterdir() if f.is_dir()]

In [4]:
from shrp.datasets.dataset_base import load_checkpoint
epoch_lst = [50]

In [54]:
for pdx in a:
    for e in range(1):
        ep = epoch_lst[e-1]
        
        ref_check, ref_lab, ref_path, ref_ep = load_checkpoint(
            path=pdx,
            edx=ep,
            weight_threshold=float("inf"),
            filter_function=None
        )
        break
    break

In [58]:
dataset_config = {
    "ds_split": [0.7, 0.15, 0.15],
    "getitem": "tokens+props",
}

In [3]:
# config to set how datasets should be downloaded. set in single place to ensure 
dataset_config = {
    'epoch_lst' : 50,
    'mode' : "vector",
    'permutation_spec' : permutation_spec,
    'map_to_canonical' : False,
    'standardize' : "l2_ind",
    'ds_split' : [1.0],  
    'max_samples' : 1000,
    'weight_threshold' : 15000,
    'precision' : "32",
    'filter_function' : None,  # gets sample path as argument and returns True if model needs to be filtered out
    'num_threads' : 8,
    'shuffle_path' : True,
    'verbosity' : 3,
    'getitem' : "tokens+props",
    'ignore_bn' : False,
    'tokensize' : tokensize
}

In [4]:
#trainset = DatasetTokens(root=[zoo_path.absolute()], train_val_test='train',  property_keys=property_keys, **dataset_config)
testset = DatasetTokens(root=[zoo_path.absolute()], train_val_test='test',  property_keys=property_keys, **dataset_config)

2023-08-17 11:30:24,601	WARNING services.py:1780 -- WARNING: The object store is using /tmp instead of /dev/shm because /dev/shm has only 1073741824 bytes available. This will harm performance! You may be able to free up space by deleting files in /dev/shm. If you are inside a Docker container, you can increase /dev/shm size by passing '--shm-size=2.91gb' to 'docker run' (or add it to the run_options list in a Ray cluster config). Make sure to set this to more than 30% of available RAM.
2023-08-17 11:30:25,697	INFO worker.py:1553 -- Started a local Ray instance.
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1000/1000 [00:19<00:00, 51.93it/s]
1000it [01:32, 10.80it/s]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1000/1000 [00:01<00:0

In [5]:
len(testset)

1000

In [6]:
testset.__get_paths__(0)

AttributeError: 'super' object has no attribute '__get_paths__'

In [13]:
testset[0]

(tensor([[ 0.0136,  0.0125,  0.0753,  ...,  0.0000,  0.0000,  0.0000],
         [ 0.0114,  0.0386, -0.0020,  ...,  0.0000,  0.0000,  0.0000],
         [-0.0549, -0.0086, -0.0125,  ...,  0.0000,  0.0000,  0.0000],
         ...,
         [ 0.0779,  0.0552, -0.1352,  ...,  0.0000,  0.0000,  0.0000],
         [ 0.0302,  0.0685,  0.0684,  ...,  0.0000,  0.0000,  0.0000],
         [ 0.0154,  0.0507, -0.0480,  ...,  0.0000,  0.0000,  0.0000]]),
 tensor([[ True,  True,  True,  ..., False, False, False],
         [ True,  True,  True,  ..., False, False, False],
         [ True,  True,  True,  ..., False, False, False],
         ...,
         [ True,  True,  True,  ..., False, False, False],
         [ True,  True,  True,  ..., False, False, False],
         [ True,  True,  True,  ..., False, False, False]]),
 tensor([[ 0,  0,  0],
         [ 1,  0,  1],
         [ 2,  0,  2],
         [ 3,  0,  3],
         [ 4,  0,  4],
         [ 5,  0,  5],
         [ 6,  0,  6],
         [ 7,  0,  7],
    

In [7]:
testset.properties.keys()

dict_keys(['test_acc', 'training_iteration'])

In [10]:
len(testset.data[0])

1